### ISSUE TITLE
Can you clarify the readme?

### ISSUE THREAD

**Issue by gotdibbs** [francodgstn/XrmJson#1]
In your readme, you state:

> Unfortunately we can't use cool libraries with Dynamics CRM so here a super simple JSON serialize/deserialize helper.

Can you clarify that statement? If you're talking about referencing other assemblies from a plugin, you can actually use ILMerge to embed external libraries into your plugins. You can read up on that [here](http://nicknow.net/dynamics-crm-ilmerge-dll-plugin/).

**Comment by francodgstn** [comment]
Yes I know, it is possible to use ILMerge but I found impossible to use JSON.Net in a Sandbox enviroment, probably due to version problem as it's mentioned in the post.

But overall I think ILMerge is a tricky way  to do the job, not really documented by Microsoft.

**Comment by gotdibbs** [comment]
@francodgstn We use JSON.NET across almost every implementation we do and it's always ILMerged. Along with another local assembly containing all the early-bound types. This includes online deployments with the sandbox in play. I think that post may be dated as we're using v8.0.3 without issue in the sandbox for an implementation of 2016 Update 1 (Online) right now.

To each their own, but it is our opinion that the code organization capabilities that ILMerge allows for far outweigh the initial setup complexity. Also, the nuget package for ILMerge referenced in that post makes the configuration 10x easier than it used to be. You just need to set individual references' copy local setting under properties in order to pick which assemblies are merged and which are not.

Just figured I'd mention it in case you weren't aware of this option since we love it so :)

**Comment by francodgstn** [comment]
Thank you @gotdibbs,  I agree with the benefits of ILMerge. I think I've to update myself an try. 
If it works  as you say, it will be very useful for my current project where I'm implementing a layer for the exchange of messages beetwen CRM and a website.
